Further front end changes
nationalarchives/ds-caselaw-public-ui pull request #139
Opened 2022-04-07 12:05 UTC by gtvj

- [x] Introduce static implementation of browse by court on homepage

2022-04-07 15:38 UTC, LewisDaleUK commented on ds_judgements_public_ui/templates/includes/browse_by_court.html
> +                <a class="judgment-browse-by-court__court-link" href="/judgments/advanced_search?court={{ court.code }}">
If you use the `url` template tag, this link won't break if (for any reason) our url scheme changes on the backend.

`href="{% url 'advanced_search' %}?court={{ court.code }}"`

2022-04-07 15:41 UTC, LewisDaleUK commented on judgments/courts.py
> +courts = [
Could we move this file into a subdirectory, called something like `fixtures`? Just to distinguish it from business-logic code that sits at the top-level. (You might need to make the subdirectory into a python module by add an empty `__init__.py` file)

2022-04-08 10:59 UTC, lozette requested changes

2022-04-08 10:59 UTC, lozette commented on ds_judgements_public_ui/templates/includes/browse_by_court.html
> +x§
Remove me!

2022-04-08 11:13 UTC, gtvj commented on ds_judgements_public_ui/templates/includes/browse_by_court.html
> +x§
Thanks - I've removed those now.

2022-04-08 11:49 UTC, lozette approved these changes

2022-04-08 16:10 UTC, merged