FCL-264 | add search breadcrumb if search query present on judgment d…
nationalarchives/ds-caselaw-public-ui pull request #1411
Opened 2024-08-29 13:57 UTC by jlhdxw

## Changes in this PR:

Adds a search breadcrumb to the judgment breadcrumb if there is a search query.

## Jira card / Rollbar error (etc)

https://national-archives.atlassian.net/browse/FCL-264

## Screenshots of UI changes:

![image](https://github.com/user-attachments/assets/3b8aae09-221a-49b0-9c36-da7bfe952d94)

2024-08-29 15:39 UTC, dragon-dxw approved these changes

2024-08-29 15:40 UTC, dragon-dxw commented
How does this look if there's a search for one of the courts? Is it 'Search results for ""'?

2024-08-29 15:45 UTC, jacksonj04 requested changes
So... this works, but I'm not convinced it actually meets the user needs, mostly because it will never include any further parameters used in the search query.

For example, an advanced search at https://caselaw.nationalarchives.gov.uk/judgments/search?per_page=10&order=relevance&query=cheese&from_date_0=&from_date_1=&from_date_2=&to_date_0=&to_date_1=&to_date_2=&court=uksc&party=&judge= only ever passes the `query=cheese` parameter to the judgment page, which in turn means anybody using the breadcrumbs to navigate back will miss a lot of that original search context.

I'm not sure what the best solution here would be; passing the whole context is messy but possibly right?

2024-08-30 02:55 UTC, jlhdxw commented
@jacksonj04 yes I missed that, good catch. I think I'll go with adding all the search query params when the user navigates to a judgment so we can add those to the breadcrumb link. I think that's the simplest approach without having to store it in some kind of state

2024-09-03 09:23 UTC, merged