[FCL-477] Handle judgements with no HTML content
nationalarchives/ds-caselaw-public-ui pull request #1663
Opened 2024-12-04 16:11 UTC by jlhdxw

## Changes in this PR:

Adding a view for PDF only documents. Doesn't include adding the new details to the summary information as we don't have that yet, and the web archive link (have wrapped in a conditional statement checking for an attribute that doesn't exist)

## Jira card / Rollbar error (etc)

https://national-archives.atlassian.net/browse/FCL-478
https://national-archives.atlassian.net/browse/FCL-481
https://national-archives.atlassian.net/browse/FCL-477
https://national-archives.atlassian.net/browse/FCL-480

## Screenshots of UI changes:

![localhost_3000_uksc_1701_999 (1)](https://github.com/user-attachments/assets/efd4d40b-4546-4311-a261-073a9a30965c)

![localhost_3000_uksc_1701_999 (2)](https://github.com/user-attachments/assets/6fdc3936-5e90-4e2a-9130-427596948c4d)

<img width="905" alt="image" src="https://github.com/user-attachments/assets/e5f3cf0f-66a8-4df2-83d5-2885839af83d">

2024-12-05 08:34 UTC, Terry-Price requested changes
Hi James,
This is looking good. There are a few things I'd like to update:

**The notification component**, can we use the Home Office blues for this, I know it's another two blue, but I think that will help it stand out as it should. Perhaps you can label these colours as such so the are not used for anything else. 

Can the width of the notification be set to the width of container. it will help keep it shallower if the messages get longer. See style guide for blues and width.

On the body text above the download button, can this use CSS balance, so it avoid widows. Same for the Web archiving text please.

The download boxes look good, will there be a Document summary tabel below them, I think that's the expectation.

You may have done this already, so apologies if you have. To apply an Aria label to the download buttons to provide context for screen readers.

2024-12-06 15:51 UTC, Terry-Price approved these changes
Thanks James.
This looks good, When the lighter grey is in it will be perfect.
As for the web archiving link, I know it's not in yet, but if we can utilise CSS balance on that, it would be less ugly than it breaks now.
thanks again for this extra mile effort.

2024-12-10 10:42 UTC, jlhdxw commented on ds_judgements_public_ui/templates/judgment/detail.html
> +  {% if document.best_human_identifier %}
Have updated this to check for document_html. I can't test this as I don't have a document that doesn't have html. Even [this judgment](https://staging.caselaw.nationalarchives.gov.uk/uksc/1701/999) has html like this:

```
<article class="judgment"><header class="judgment-header"></header><section class="judgment-body"><p></p></section></article>
```

2024-12-10 10:55 UTC, jlhdxw commented on ds_judgements_public_ui/templates/judgment/detail.html
> +  {% if document.best_human_identifier %}
I don't think we've got a way of doing this with xml? In terms of the design, the "pdf only" and "with html" download options are so different from each other we'd have to have extra logic to check when showing the PDF download option if there is XML to determine which download style to show.

2025-02-06 10:33 UTC, jacksonj04 approved these changes

2025-02-06 12:49 UTC, merged