Mobile view buttons panels fix
nationalarchives/ds-caselaw-public-ui pull request #583
Opened 2023-03-01 11:02 UTC by Donna-H

## Changes in this PR:
Fix mobile view, The search button was no longer as wide as the text box, fix styling issues on the ‘Update filters’ button, and on the label text above the search buttons

## Trello card / Rollbar error (etc)
https://trello.com/c/AQU5XFb7/536-mobile-view-buttons-label-text
## Screenshots of UI changes:

### Before

![before-mobile-update-button](https://user-images.githubusercontent.com/75584408/222121222-2cdca26a-67ee-46bc-929c-12dc045dd2c9.png)

### After
[update-mobile-after.webm](https://user-images.githubusercontent.com/75584408/222120997-d0108dd7-1659-4311-b724-f513b7434c74.webm)
- [ ] Requires env variable(s) to be updated

2023-03-01 11:12 UTC, Terry-Price requested changes
Hi Donna,
Thanks for this.

I did notice that the form labels have differing spaces between them and the text fields. Can those be fixed to be consistent.

Also, Looking at the new styles, was unsure about why the margin is 1px. Seems a bit small, should it be 0?

The blue button at the bottom is still full width on mobile, could you look to match the Search button at the top?

I can help maybe if you want to pair up later?

2023-03-01 11:27 UTC, Donna-H commented
> Hi Donna, Thanks for this.
> 
> I did notice that the form labels have differing spaces between them and the text fields. Can those be fixed to be consistent.
> 
> Also, Looking at the new styles, was unsure about why the margin is 1px. Seems a bit small, should it be 0?
> 
> The blue button at the bottom is still full width on mobile, could you look to match the Search button at the top?
> 
> I can help maybe if you want to pair up later?

@Terry-Price the trello card stated " search button was no longer as wide as the text box" so submit button at bottom is  as top search button now changed to as wide as text box

2023-03-02 10:29 UTC, jacksonj04 requested changes
I think this could be rebased and all these commits squashed into one.

2023-03-02 17:52 UTC, Donna-H commented
@jacksonj04 rebased please check all is okay

2023-03-07 14:50 UTC, jacksonj04 commented
@Donna-H if we can squash them into one commit I think this is good to go!

2023-03-09 10:39 UTC, jacksonj04 approved these changes

2023-03-09 15:08 UTC, Terry-Price approved these changes
we'll pick up any issues with this when Tim is around.

2023-03-09 15:11 UTC, merged