Update homepage header
nationalarchives/ds-caselaw-public-ui pull request #706
Opened 2023-05-18 11:46 UTC by Donna-H

## Changes in this PR:
Update homepage header -revisiting the use of the TNA logo on the site- use the narrow version of the logo- users to access the page content more quickly and so this work will reduce the scrolling required.

## Trello card / Rollbar error (etc)
https://trello.com/c/XSEVm87x/912-pui-homepage-header
## Screenshots of UI changes:

### Before
![old-desktop](https://github.com/nationalarchives/ds-caselaw-public-ui/assets/75584408/768b7554-9f92-4731-bf89-83ad13a35962)
![old-mobile](https://github.com/nationalarchives/ds-caselaw-public-ui/assets/75584408/01802f93-7eb3-4df5-9ef6-3486ae3af738)

### After
![new-desktop](https://github.com/nationalarchives/ds-caselaw-public-ui/assets/75584408/4948ee51-bb1a-45a2-a463-60006702945e)
![new-mobile](https://github.com/nationalarchives/ds-caselaw-public-ui/assets/75584408/f488aa80-9b96-4021-ab98-b0aaeb3f2740)

- [ ] Requires env variable(s) to be updated

2023-05-18 12:05 UTC, jacksonj04 requested changes
A couple of tweaks to make, but this is looking so much cleaner already.

- The typography purist in me is screaming at the fact that "Find Case Law" and the TNA logo are top-aligned and not baseline-aligned.
- This PR says it's about the homepage, but we're ditching the logo image which is used everywhere, so all of the judgment pages look weird
- The mobile breakpoint is set too wide, so it's possible to make the viewport narrow enough it clips the logo before it breaks to mobile
- The flexbox isn't centring properly, so if your viewport is wider than the maximum breakpoint then it hangs over the left margin and leaves a load of space to the right.

It might be easier to consider slicing this into two distinct bits; "Find case law" and "Delivered by..." in one include, and then the service blurb in another. That way we can also repurpose the top include on judgment pages, pop the breadcrumbs back underneath, and tidy it all up in one clean move.

2023-05-18 12:42 UTC, Terry-Price commented on locale/en_GB/LC_MESSAGES/django.po
> +" decisions from 2003"
Can we consider saying '...since 2003.'

2023-05-18 12:45 UTC, Terry-Price commented on ds_judgements_public_ui/templates/includes/logo.html
>      <img class="page-header__logo"
Is there an alt text tag for the logo? I cant see one.
Can you change the 'Delivered by' text be #FFFFFF?

2023-05-18 12:50 UTC, Terry-Price commented on ds_judgements_public_ui/static/images/tna_logoOLD.svg
on the mobile, the TNA logo width needs to be 200px. This will match the guidance site header banner.

![Screenshot 2023-05-18 at 13 49 56](https://github.com/nationalarchives/ds-caselaw-public-ui/assets/102584881/e6c57e90-d5ed-468b-b23e-8131978f7367)

2023-05-18 12:54 UTC, Terry-Price commented on locale/en_GB/LC_MESSAGES/django.po
> +" decisions from 2003"
we may need to control the yellow text line length on desktop viewport so it doesnt run into the logo area like that.

2023-05-18 16:13 UTC, jacksonj04 commented
Some touch-ups to move things to make more use of flexbox and tighten up some spacing, and to implement the slimline logo on judgment pages.

![localhost_3000_ (1)](https://github.com/nationalarchives/ds-caselaw-public-ui/assets/619082/0f902845-5d5d-45d7-b100-d949b9ee2bb7)

![localhost_3000_ewhc_ch_2023_1130](https://github.com/nationalarchives/ds-caselaw-public-ui/assets/619082/a20b0e90-7052-45bd-a079-368811b6c47b)

2023-05-19 13:14 UTC, jacksonj04 approved these changes

2023-05-19 14:32 UTC, Terry-Price commented
all good.

2023-05-19 14:33 UTC, Terry-Price approved these changes
all good, well done Donna,

2023-05-19 14:56 UTC, merged